resources:
  ping_rest_resource:
    GET:
  labs_experiment_item_rest_resource:
    GET:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
  labs_experiment_list_rest_resource:
    GET:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
  subject_list_rest_resource:
    GET:
      supported_formats:
        - jcms_json
      supported_auth:
        - basic_auth
  subject_item_rest_resource:
    GET:
      supported_formats:
        - jcms_json
      supported_auth:
        - basic_auth
  podcast_episode_list_rest_resource:
    GET:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
  podcast_episode_item_rest_resource:
    GET:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
  person_list_rest_resource:
    GET:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
  person_item_rest_resource:
    GET:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
link_domain: null
_core:
  default_config_hash: E9VXRiWZNet4YVBv8j9WQmTlgb-rOjo0MiCSdgV0Guw
