resources:
  labs_experiments_item_rest_resource:
    GET:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
  labs_experiments_list_rest_resource:
    GET:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
  subjects_list_rest_resource:
    GET:
      supported_formats:
        - jcms_json
      supported_auth:
        - basic_auth
  subjects_item_rest_resource:
    GET:
      supported_formats:
        - jcms_json
      supported_auth:
        - basic_auth
  podcast_episodes_list_rest_resource:
    GET:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
  podcast_episodes_item_rest_resource:
    GET:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
  person_list_rest_resource:
    GET:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
  person_rest_resource:
    GET:
      supported_formats:
        - json
      supported_auth:
        - basic_auth
link_domain: null
_core:
  default_config_hash: E9VXRiWZNet4YVBv8j9WQmTlgb-rOjo0MiCSdgV0Guw
